### ISSUE TITLE
Is there something like launch api in ros1 for launch library in ros2?

### ISSUE THREAD

**Issue by Fricodelco** [ros2/launch#486]
Am I able to run and kill launch file from python script? In ros1 I did it with launch api for python, how could I do it in ros2?

**Comment by hidmic** [comment]
I'm not sure if you've seen [ROS support guidelines](http://wiki.ros.org/Support), but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org) instead.

The rationale for asking all kind of questions in a single place is:

- There are many more people reading questions there, so your chances on getting an answer in a timely manner are much higher.
- In the future, other users will search there for similar problems, and may find your question and potential answers. Here, it'll get lost once this ticket is closed.
- The issue tracker in this repository is used to track bug reports, feature requests, etc. Your question does not fit that description.

Therefore, I will close this ticket here, for now. If you've asked your question on [answers.ros.org](http://answers.ros.org), please feel free to add a link to it here so that future readers may find your question.
