### ISSUE TITLE
[launch_testing] Sequential unit tests?

### ISSUE THREAD

**Issue by chancecardona** [ros2/launch#489]
Hello, I've been attempting to migrate some unit/integration tests that were originally being done with rostest into the launch_testing framework. Essentially my question is how do I run unit tests non-concurrently? The tests involve starting a simulation and testing a controller by measuring states from the simulation after commands are run. Previously I had a test for one type of movement, then another type of movement, but as these tests check the changes from the simulation they need to be ran sequentially else they'll interfere with each other. I am wondering if there is any good way to just specify that the tests shouldn't be ran in parallel? Like with a decorator or if there's some workaround or if I'm just using this framework completely incorrectly (and if so how should I be doing this? I'd prefer to keep the testing under one framework as was possible in rostest). 
Thank you for the help.

Using Foxy binary install on Ubuntu 20.04 if it's of any help

**Comment by hidmic** [comment]
I'm not sure if you've seen [ROS support guidelines](http://wiki.ros.org/Support), but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org) instead.

The rationale for asking all kind of questions in a single place is:

- There are many more people reading questions there, so your chances on getting an answer in a timely manner are much higher.
- In the future, other users will search there for similar problems, and may find your question and potential answers. Here, it'll get lost once this ticket is closed.
- The issue tracker in this repository is used to track bug reports, feature requests, etc. Your question does not fit that description.

Therefore, I will close this ticket here, for now. If you've asked your question on [answers.ros.org](http://answers.ros.org), please feel free to add a link to it here so that future readers may find your question.
