### ISSUE TITLE
Alaunch.py files use IfCondition statements

### ISSUE THREAD

**Issue by miku54** [ros2/launch#504]
Hello, I started node An in the Alaunch.py file and set a parameter, useakm=LaunchConfiguration ('useakm','true''). The change takes effect when I run Alaunch.py alone, but when I call the Alaunch.py file in Blaunch.py, useakm=LaunchConfiguration (' useakm','false'), this change does not take effect, what should I do?

**Comment by hidmic** [comment]
I'm not sure if you've seen [ROS support guidelines](http://wiki.ros.org/Support), but we kindly ask to raise questions like this on [answers.ros.org](http://answers.ros.org/) instead.

The rationale for asking all kind of questions in a single place is:

There are many more people reading questions there, so your chances on getting an answer in a timely manner are much higher.
In the future, other users will search there for similar problems, and may find your question and potential answers. Here, it'll get lost once this ticket is closed.
The issue tracker in this repository is used to track bug reports, feature requests, etc. Your question does not fit that description.
Therefore, I will close this ticket here, for now. If you've asked your question on [answers.ros.org](http://answers.ros.org/), please feel free to add a link to it here so that future readers may find your question.
