### ISSUE TITLE
Load node configuration or parameters during launch

### ISSUE THREAD

**Issue by janncker** [ros2/launch#67]
## Feature request
Many nodes need configuration or parameters to make it flexible, however I didn't found a good example to show how to load parameters, as _rosparam_ or _param_ do in ROS. I think it's a necessary feature to ROS2. 

#### Feature description

Similar as _rosparam_ and _param_ in ROS.

#### Implementation considerations

Define some keywords in Descriptors, load or parser the parameters and configurations, pass them to node. Node set them through ParameterService.

**Comment by wjwwood** [comment]
Thanks for taking the time to bring this up. However, we're aware of the need for this feature and we consider it part of the broader "Python-based launch with stable API, introspectable, optional XML frontend" from the roadmap:

https://github.com/ros2/ros2/wiki/Roadmap

I know it's misleading at the moment, but this repository and the packages in it are just the technical foundation for something like ROS 1's roslaunch. It does not, however, contain any of the familiar primitives like nodes, remapping, and parameter setting from ROS 1's roslaunch just yet.

This particular feature is also blocked by needed work on the parameters and setting them programatically or from the command line, see: https://github.com/ros2/ros2/issues/432

This is definitely on our short list of things to get done next, and hopefully soon the above roadmap link will have more details on our plan until summer.

Since this is covered more broadly by our other planning processes, I'll go ahead and close this, but when the roslaunch like tool is finished, feel free to iterate on the behavior or style of this particular feature with us.
